services:
# Banco de dados PostgreSQL
  postgres:
    image: postgres:latest
    container_name: fluxocaixa_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - fluxocaixa_network

# RabbitMQ para mensageria
  rabbitmq:
    image: rabbitmq:3-management
    container_name: fluxocaixa_rabbitmq
    ports:
      - "5672:5672"  # Porta para conexão AMQP
      - "15672:15672"  # Porta para interface de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    networks:
      - fluxocaixa_network

# Redis para caching
  redis:
    image: redis:latest
    container_name: fluxocaixa_redis
    ports:
      - "6379:6379"
    networks:
      - fluxocaixa_network

# prometheus para monitoramento
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - fluxocaixa_network

# Grafana para visualização de métricas
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - fluxocaixa_network

# Serviço de Carga de Dados
#  k6:
#    image: carga-k6
#    container_name: carga-k6
#    networks:
#      - fluxocaixa_network

# Serviço de Lançamentos
  lancamentos:
    image: fluxocaixa_lancamentos
    container_name: fluxocaixa_lancamentos
    build:
      context: ./src/FluxoCaixa.Lancamentos
      dockerfile: Dockerfile
    ports:
      - "5005:8080"
    environment:
      - DefaultConnection=Host=postgres;Port=5432;Database=fluxocaixa_lancamento;Username=admin;Password=admin123
      - RabbitMQ:HostName=rabbitmq
      - RabbitMQ:Port=5672
      - RabbitMQ:UserName=admin
      - RabbitMQ:Password=admin123
      - RabbitMQ:VirtualHost=/
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - fluxocaixa_network

# Serviço de Consolidado Diário
  consolidado:
    image: fluxocaixa_consolidado
    container_name: fluxocaixa_consolidado
    build:
      context: ./src/FluxoCaixa.Consolidado
      dockerfile: Dockerfile
    ports:
      - "5004:8081"
    environment:
      - DefaultConnection=Host=postgres;Port=5432;Database=fluxocaixa_consolidado;Username=admin;Password=admin123
      - RabbitMQ:HostName=rabbitmq
      - RabbitMQ:Port=5672
      - RabbitMQ:UserName=admin
      - RabbitMQ:Password=admin123
      - RabbitMQ:VirtualHost=/
    depends_on:
      - postgres
      - rabbitmq
      - redis
    networks:
      - fluxocaixa_network
      
# Volumes para persistência de dados
volumes:
  postgres_data:

# Rede para comunicação entre os containers
networks:
  fluxocaixa_network:
    driver: bridge
